### PR TITLE
Relax upper bounds of QuickCheck

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Review by msakai — APPROVED** [review]
LGTM!

**Comment by msakai** [comment]
I edited Cabal file metadata of `extended-reals-0.2.3.0` on Hackage and also released a new version `extended-reals-0.2.4.0`.

@Bodigrim,
I invited you as a collaborator to this repository.
And can I add you to the maintainer group of this package on Hackage too?

**Comment by Bodigrim** [comment]
Thanks! Sure, please add.

**Comment by msakai** [comment]
Thanks!
I added you to the maintainer group.

**Pull request merged**
